### ISSUE TITLE
Direction Clarification

### ISSUE THREAD

**Issue by chuckeymonkey** [Hube2/acf-post2post#1]
Could you elaborate on how to accomplish bidirectional post/relation fields. Perhaps supply an example or better steps?

If I could get this working, it would be amazing!

PS- Thank you for the hard work

**Comment by Hube2** [comment]
Create a field on the same name on all of the posts to be related. The field must be at the top level, in other words not inside a repeater or a flexible content field.

If you are doing something like relating Blog Posts to other Blog posts then you just need to set up a field group with a relationships post for the blog posts and the plugin should take care of the rest.

If you are creating a relationship between different post types then you need to make sure that a relationship field with the same field name exists for both post types. 
For example if I wanted to create a relationship between posts and pages I would create a field in a field group for each. For "post" post type I might have:
```
Field Label: Related Pages
Field Name: related_posts_pages
```
And on the "page" post type I would create:
```
Field Label: Related Posts
Field Name: related_posts_pages  // same field name as above
```
Let me know if that helps you or where I can explain further. Also let me know if it's not working. It was a working when I last worked on it 3 weeks ago.

**Comment by Hube2** [comment]
I've been doing some testing and it appears that acf is no longer passing the post_id to my function for some reason. I'm working on it. odd.

**Comment by Hube2** [comment]
Thank you for reporting this bug, now I'm wondering how long it hasn't been working. Can you please download the latest version and try it again.

**Comment by chuckeymonkey** [comment]
Doing a quick test, it seems to be working now! Thank you!

**Comment by Hube2** [comment]
I think I may have done some code optimization after my final test and a bug crept in, should have given it another test and I would have found my typo.

Like I said, I'm very glad that someone said something, otherwise the bug would have been there until I needed to use it on the site I'm currently working on. Thanks again for reporting it.
