### ISSUE TITLE
A problem with serialization

### ISSUE THREAD

**Issue by certainlyakey** [Hube2/acf-post2post#12]
Hi!

I'm not sure if it's a problem related to the plugin or ACF itself. When post2post saves the current post id to the DB postmeta of the post it's being related to, it seems that in the serialized data the post id is not always surrounded by commas. That makes it harder to do LIKE-based reverse queries [described in the ACF documentation](https://www.advancedcustomfields.com/resources/querying-relationship-fields/), which tells us to surround the related post id with quote marks to avoid intersections with other ids.

A dirty workaround of mine for now is to use second meta query which checks also for `:` and `;` around the id.

**Comment by Hube2** [comment]
For the most part I'm relying on WordPress's automatic serialization of array values... just did a test and you are correct. It appears that ACF is storing the post IDs as string values and I am storing them as integer values and this is probably the difference. I'll work on an update.

**Comment by Hube2** [comment]
I'm pretty sure I have this corrected, but it won't update existing values already saved unless the post is updated.

**Comment by certainlyakey** [comment]
This is so great. Thanks for reacting and going ahead with fixing this so quickly!
