### ISSUE TITLE
Add composer.json

### ISSUE THREAD

**Issue by ruscon** [Hube2/acf-post2post#14]
sample
https://github.com/nlemoine/acf-country/blob/master/composer.json

**Comment by Hube2** [comment]
Thanks for the request. I'm not very familiar with composer and I'm not sure what would need to be in this file. I'll look into adding it when I have time. Will gladly accept a pull request if someone else wants to add what's needed.

**Comment by ruscon** [comment]
You must register on the in https://packagist.org/ ?
You can set auto updating once from the git
See https://packagist.org/about -> "How to update packages?"
