### ISSUE TITLE
Are exceptions enabled ?

### ISSUE THREAD

**Issue by fmerlat** [Hube2/acf-post2post#18]
Hi,
Is this possible to have exceptions ?
I mean I have some Relationship fields which I need them to be bidirectional, using your plugin, and I have some Relationship fields I'd like to keep them unidirectional.
Thank you.

**Comment by Hube2** [comment]
Currently, no. If the field meets the criteria it will automatically be bidirectional.

I could possibly add a filter to allow the exclusion of some fields.

**Comment by fmerlat** [comment]
That would be great !
Good job anyway, useful plugin.

**Comment by Hube2** [comment]
## Field Exeptions

You can disable automatic bidirectional relationships for specific field keys using the filter
```
// field_XXXXXXXX = the field key of the field
// you want to disable bidirectional relationships for
add_filter('acf/post2post/update_relationships/key=field_XXXXXXXX', '__return_false');
```

**Comment by fmerlat** [comment]
Thank you so much for the Plugin update !
Great job !
