### ISSUE TITLE
bi-directionally sync after post import

### ISSUE THREAD

**Issue by matthiashonert** [Hube2/acf-post2post#19]
Hey John, I love your plugin. It's great tool. 

For a musican website I am currently trying to link two CPT named tours and dates via CSV import.

I'm using the WP All Import plugin right now and I notice that the posts are not bi-directionally linked after the import. 
After date posts import the field "tours" is perfectly linked with existing tours. But when I look at the tour post, the dates aren't selected/linked. Only when I update a date post, then everything is fine and bi-directionally linked.
Do you have experience with importing or how I could trigger your plugin to updating?

**Comment by Hube2** [comment]
Unfortunately, no. I have experience using WPAI. It does not trigger the acf/update_value hook which this plugin requires to function. WPAI does have it's own hook that triggers after a post in imported, but I'm not really sure it's usable. http://www.wpallimport.com/documentation/advanced/action-reference/

This is just a thought, and I can't give any guarantees
```
add_action('pxmi_saved_post', 'my_wpai_saved_post');
function my_wpai_saved_post($post_id) {
  // get the relationship field for this post, without formatting
  $value= get_field('your-relationship-field', $post_id, false);
  if ($value) {
    // update the same field, this might force the hook and cause the update
    update_field('your-relationship-field', $value, $post_id);
  }
}
```

**Comment by jungermedia** [comment]
@matthiashonert Not sure if you ever got this going. 

I ran into the same issue, and rather than try and hook into WP All Import, I created a quick front-end query adapting @Hube2's code and it worked like a charm.

Here's mine: adjust your $args and field_name appropriately.

`
<?php 
    $args = array(
        'post_type' => 'location',
        'posts_per_page' => 100,
    );
    $myposts = get_posts($args);
    foreach ($myposts as $mypost){
    	echo $mypost->post_title . '<br />';
    	$id = $mypost->ID;  
		$value = get_field('field_name', $id, false);
		  if ($value) {
		    update_field('field_name', $value, $id);
		  }
    }?>`

**Comment by Hube2** [comment]
The main issue with importing and a bi-directional update is that the value imported represents a post ID. If you are importing new posts then the posts imported will most likely not have the same post IDs as they had when they were exported. To top this off, some of the posts may be imported after the relationship is created. This makes the entire process extremely complicated. You need to know the old ID and somehow connect this to the new ID when the post is created. Then you need to modify the value being imported to the new ID before WPAI stores the value and then you can run then you can call `update_field()` from one side of the relationship or the other.
