### ISSUE TITLE
Filter options in relationship?

### ISSUE THREAD

**Issue by powell1x** [Hube2/acf-post2post#20]
Hey John! Great work here.  Question for you - I have a relationship set up between companies and jobs.  The field shows open jobs when looking at the company page, and the company on the job listing.  It works great.

Companies are CPTs, and I'm allowing submission of jobs. I only want users to be able to post jobs to companies that they "own" (are the authors of).  Is there a way I can filter that list CPTs that appears in the relationship field in that fashion?

Thanks!

**Comment by Hube2** [comment]
You're looking for this https://www.advancedcustomfields.com/resources/acf-fields-relationship-query/ or possibly this https://www.advancedcustomfields.com/resources/acf-fields-post_object-query/  If you need help on using them you should post a question on the ACF forum.
