### ISSUE TITLE
Add support for linking across Multisite posts

### ISSUE THREAD

**Issue by harryrichardson** [Hube2/acf-post2post#29]
It would be excellent to be able to relate posts in a bidirectional way between multisites. 

This would be primarily for linking multisite content from different languages e.g:

Multisite 1 - Page: Home En-US - [english] 
Multisite 2 - Page: Home ES-ES - [spanish]

A bi-directional relationship to link the two together.

Is this something that could be introduced as core or an add-on extenstion?

**Comment by Hube2** [comment]
This is not something that can be done with this plugin. This would need to be a special field type that would need to be build from the ground up. Relationship and post object fields in ACF will not work across different sites in mutlisite.
