### ISSUE TITLE
One to many relationship issue

### ISSUE THREAD

**Issue by jnaklaas** [Hube2/acf-post2post#30]
There is an issue using acf-post2post with one-to-many relationships.

I have a custom post type `subproject`, which can have many `apartment`'s.
Both have a custom field with name `subproject_apartments_relationship`.
The custom field type for `subproject` is a `relationship` since it can have many apartments. The custom field type for `apartment` is `post_object` since it has only one subproject.

Let's say there are two subprojects, "subproject-A" and "subproject-B".

Say "apartment-1" is currently linked to "subproject-A". In the "subproject-B" post, I add "apartment-1". After checking "aparment-1", the relationship field shows "subproject-B". So far so good. But when I take a look at the "subproject-A" post, it still shows "apartment-1".

Starting situation
- apartment-1 has subproject-A
- subproject-A has apartment-1
- subproject-B has no apartments

Change subproject to "subproject-B" from within the "apartment-1" post
- apartment-1 has subproject-B
- subproject-A has no apartments
- subproject-B has apartment-1

Back to starting situation, add "apartment-1" in the "subproject-B" post
- apartment-1 has subproject-B
- subproject-A has apartment-1        ---> this is not what I expect
- subproject-B has apartment-1

Please help!

**Comment by Hube2** [comment]
I have been struggling with this for a while. The problem is that I can't figure out a way to do this without creating the potential for an infinite loop where the update of a field triggers the update on related posts which could trigger the update of the same post again.

**Comment by jnaklaas** [comment]
I see... any chance you might look into this again in the near future? I took a quick look at the source code, but it would take me quite some time just to fully grasp what is going on there, let alone figure out how to fix this issue :-) .

**Comment by Hube2** [comment]
I'm actually thinking about it now. Currently, it uses update_post_meta() directly instead of calling update_field(). This bypasses the endless loop possibility. The only real way that I can cause a cascading update of all related posts in a chain would be to use update field on the other post which would cause the filters in plugin to be called and do their thing, but this is where the danger up the infinite loop is.

**Comment by Hube2** [comment]
I just pushed a change here, can you test it and see if it corrects the problem you're seeing

**Comment by Hube2** [comment]
Also do not forget, by default this plugin will not overwrite a post object field. If the post object field only allows a single entry and another post tries to add the relationship, if the post object field already has a value then it will not be overwritten. In order for this to happen you must add a filter to tell this plugin that you want the value to get overwritten
```
add_filter('acf-post2post/overwrite-settings', 'my_overwrite_settings');
function my_overwrite_settings($settings) {
	$settings['my_field_name'] = array(
	  'overwrite' => true
	);
	return $settings;
}
```

**Comment by Hube2** [comment]
I completely forgot about about the need for overwrite settings filter when I first read your post. The reason that I did not make it overwrite by default was backwards compatibility. When I first published this plugin no fields would be overwritten and there wasn't a way to make it do so. Adding the ability to have fields overwritten was the addition and that is the reason it requires the filter.

I did some extensive testing with the scenario you have and everything seems to be working correctly, provided I add the overwrite filter to functions.php.

**Comment by jnaklaas** [comment]
Gotten even worse now. Based on previous example, when adding "apartment-1" in the "subproject-B" post:

    apartment-1 has subproject-B
    subproject-A still has apartment-1 ---> this is not what I expect
    subproject-B still has nothing ---> :-(

Overwrite settings don't seem to have any impact fwiw.
Perhaps I should stick with one-directional relationships for now.

**Comment by Hube2** [comment]
I have reverted the changes here, you should reinstall.

Are you editing one post at a time and reloading the others? Like I said, I did extensive testing the other day using a relationship/post object relationship and everything is working as I expect it to with the overwrite filter in place.

**Comment by jnaklaas** [comment]
Okay. I'm developing a plugin, and was adding the filter directly in the plugin's main script right after requiring the post2post plugin. I added the filter in the constructor of my plugin's main class and now it is working. So far it seems to be working! Thanks a lot!
