### ISSUE TITLE
Activate the plugin only for specific field

### ISSUE THREAD

**Issue by simonemanfre** [Hube2/acf-post2post#40]
Instead of excluding fields one by one using the filter:
`add_filter('acf/post2post/update_relationships/key=field_XXXXXXXX', '__return_false');`

It's possible to disable all the relationship fields and enable only the field that i want?

In my experience there are few times when it is needed to enable a bidirectional relationship between fields, and in this way if I add in the future a new relationship field which doesn't need a bidirectional relationship I don't have to edit my code and exclude that field.

**Comment by Hube2** [comment]
I added a filter 'acf/post2post/update_relationships/default" and added it to the documentation. Returning false on this filter will disable all fields and then you must use the previous filter to enable them.

**Comment by simonemanfre** [comment]
Great, that's exactly what I meant.
Thanks a lot!
