### ISSUE TITLE
User Field

### ISSUE THREAD

**Issue by chuckeymonkey** [Hube2/acf-post2post#5]
I know its a little different, but it is close enough in concept I figured I'd ask. Do you have any plans to include the "User" field in any future updates? For instance allowing users to easily be assigned to other users (A "Manager" role who is assigned "Employee" roles - so the Manager would have multiple employees and the Employees would only have one manager)

**Comment by Hube2** [comment]
I'm not completely sure I understand how it would work, mostly because the user field relates something to a user. If this user field was on a user profile page it might be possible, but it would take some time to work out the details.

**Comment by Hube2** [comment]
I create a simple example of what's needed to create a 2 way relationship and added it to my acf filters and functions repo. Doing this for a user field would be very similar, the main difference that that you'd need to get the user ID's and look in the _usermeta table if the relationship fields are on the user profile page. If the fields are actually located somewhere else then, to be honest, I'm not sure how to do that, I'm not sure that it would be possible. Anyway, the example is here https://github.com/Hube2/acf-filters-and-functions/blob/master/acf-reciprocal-relationship.php

**Comment by Hube2** [comment]
sorry, this is beyond the scope of this plugin. Should be a separate plugin
