### ISSUE TITLE
Question: Looks good but is it stable for ACF 4?

### ISSUE THREAD

**Issue by fl0ri** [Hube2/acf-post2post#8]

**Comment by Hube2** [comment]
No, it does not work in ACF4. This uses a function named acf_get_field_groups() that does not exist in 4 to find the field for the related post. In ACF 4 there isn't a way to search and find a field for another post based on the field name. In 4 you need to create filters that work only for specific fields. I have an example of doing this here https://github.com/Hube2/acf-filters-and-functions/blob/master/acf-reciprocal-relationship.php. There is also an example of this on the ACF site https://www.advancedcustomfields.com/resources/bidirectional-relationships/
