### ISSUE TITLE
Make installable via composer?

### ISSUE THREAD

**Issue by certainlyakey** [Hube2/acf-post2post#9]
Hi, thanks for the useful plugin. 

Would it be possible to make it available via Packagist repository (or in some other way)? I use [this method](https://github.com/PhilippBaschke/acf-pro-installer) to make ACF itself installable with Composer.

Thanks!

**Comment by Hube2** [comment]
I don't use composer, so I'm not exactly sure what is required to make this possible. If you know what it is that I need to add, or you send me a pull request with the additions I would be happy to add it in. Not sure if it makes any difference for this but this plugin is now also available on wordpress.org.

**Comment by certainlyakey** [comment]
Nice to know! It's much easier to add those packages that are on Wordpress.org, it can be done via wpackagist.org. So this should be resolved now. Thanks!

**Comment by Hube2** [comment]
Yep, I've recently published several of my more popular and mostly stable ACF addons to wordpress to make it easier for people to find them and use them. Glad that helped you. This one is at https://wordpress.org/plugins/post-2-post-for-acf/
